### ISSUE TITLE
DAA score and minting kaspa

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1259]
The DAA gives is 1b/s only locally, meaning that if we want to measure time in the system we have to track blocks that were in the DAA window, because only they have affected the difficulty.

For that we can inherit the "DAA Score" from the SP and add blocks any block from the mergeSet that is in the blueWindow of the block.
We also need to mark those block for kaspa rewards, that way we can control the inflation rate.

This is the same as block height under k=0 and rejecting red blocks (bitcoin).

 Note that according to #1029 we will only give reward to blocks that have affected the DAA, and obviously the reward of red blocks goes to the merging block according to #1029

**Comment by elichai** [comment]
About a week of work

**Comment by someone235** [comment]
We need to use the DAA score instead of blue score in the following places:
* Calculation halving time
* Lock times
* UTXO entries

**Comment by someone235** [comment]
The code should be changed in the following way:
1. The DAA should be calculated from the block POV instead of its selected parent POV, so we'll be able to check which blocks from its merge set were part of the DAA window.
In order to do that, we also need to calculate GHOSTDAG before validating the difficulty.
2. When validating the block difficulty, we should also calculate the DAA score and the added DAA blocks and save them in corresponding stores.
3. We should use the DAA score instead of blue score in the following places: Calculation halving time, lock times, and UTXO entries
