### ISSUE TITLE
Write unit tests for error cases in ValidateAndInsertBlock

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1373]
Right now most error cases in `validateAndInsertBlock` aren't covered, we should write more tests that insert invalid blocks in different ways to trigger different ruleErrors.

**Comment by stasatdaglabs** [comment]
Fixed by the following, among others:
https://github.com/kaspanet/kaspad/pull/1397
https://github.com/kaspanet/kaspad/pull/1398
https://github.com/kaspanet/kaspad/pull/1405
https://github.com/kaspanet/kaspad/pull/1408
https://github.com/kaspanet/kaspad/pull/1415
https://github.com/kaspanet/kaspad/pull/1420
https://github.com/kaspanet/kaspad/pull/1422
