### ISSUE TITLE
If kaspad runs out of addresses - no new ones will be ever added

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1588]
If, for any reason, AddressManager ran out of addresses, then ConnectionManager.checkOutgoingConnections would get 0 addresses from addressManager.RandomAddresses, and will simply do nothing.

Currently we request addresses from DNSSeeder only on start, so it is no help either.

Things we can do at such situations:
1. Send GetAddresses to all peers (if any such exist)
2. Request addresses from DNSSeeder.

**Comment by elichai** [comment]
I think this is important, and might be related to the fact that when you run a node on a laptop and put it to sleep, when you wake it up (probably under a different IP address) it might not connect to anyone (I assume it disconnects because it can't reach them, then it removes them from AddressManager, and now it's empty and has no peers)
